### ISSUE TITLE
ModuleNotFoundError: No module named 'apposlc'

### ISSUE THREAD

**Issue by AlexVaPe** [cslab/pyoslc#26]
Hi,

I'm trying to use pyOSLC SDK in order to develop my own adapter but I'm always getting the same error "ModuleNotFoundError: No module named 'apposlc'".

I'm following the 'develop' branch, and following the steps, but when I type "PyOSLC run" I'm getting that error.

I'm using virtualenv 20.10.0 and I can't force the "mkvirtualenv -p `which python2.7`myenv" as virtualenv 20.10.0 is not compatible with python2.7. Either way, I don't know if the problem is due to this fact or something else.
<img width="757" alt="Captura de pantalla 2021-11-27 a las 12 10 13" src="https://user-images.githubusercontent.com/45622121/143678753-91a3e7c8-0896-46b4-80b9-cc8121fc4b9a.png">
<img width="770" alt="Captura de pantalla 2021-11-27 a las 12 11 09" src="https://user-images.githubusercontent.com/45622121/143678781-461627f4-a9f6-4117-93f4-779ca35b2609.png">

Error logs:

<img width="764" alt="Captura de pantalla 2021-11-27 a las 12 12 49" src="https://user-images.githubusercontent.com/45622121/143678834-c52ca8f5-d654-4adc-bb13-2e433e14e400.png">

I don't know what to do at this point. Can you help me please?

Thanks

**Comment by yichencon** [comment]
Hi AlexVaPe,

The module 'apposlc' is an example to show how to start a pyoslc application and it is not included as source file in PyOSLC package. Therefore, you need to download it from the repository and put it to your project folder manually. But after doing this, you may not able to run 'pyoslc run', since there is still an issue in pyoslc server. So a wordaround is using the command '(myenv) python <your project folder>/apposlc/wsgi.py' to start the wsgi application directly. 

I hope this can help you. 

Best regards,
Yi

**Comment by isccarrasco** [comment]
Hello @AlexVaPe,

I reviewed the error messages that you had shared, and it seems like you followed the steps described in the README file for the creation of OSLC API, unfortunately the version you used it was outdated.

I just merged a new version of the README file in which I'm describing step by step how to implement the OSLC API using the new classes and the new concepts like Adapters and Resources, please take a look on this new version to see if this solve your issue.

Regards!

**Comment by AlexVaPe** [comment]
Hi,

Thanks both.

I've tried with the new version you updated and now I'm getting this error:

<img width="763" alt="Captura de pantalla 2021-12-04 a las 9 05 03" src="https://user-images.githubusercontent.com/45622121/144702462-afc47ef5-8009-4ddb-9d7d-2149ae1084af.png">

I've created myenv environment exactly how you describe it, and followed the steps, but it still not works.

Regards!

**Comment by AlexVaPe** [comment]
Hi,

Could you please check this?

I'm still getting the same error even with the last commit.

Thanks

**Comment by isccarrasco** [comment]
Hello @AlexVaPe,

I took a look on the issue that you have reported, I just have done a clean configuration of a virtual environment using the version of Python 2.7.18, I also did follow the steps described in the README to create the API, and finally I ran the application through the command line as you have done.

I did these steps on Windows and Mac to validate and trying to replicate the issue, but I can not see any error on my end.

Can you please share more information about what is the content of the `wigs.py`, `resource.py` and `adapter.py` for trying to replicate the issue in my local environment?

I'm attaching a screenshot showing how it works on my local.

<img width="1086" alt="Screen Shot 2021-12-16 at 19 56 31" src="https://user-images.githubusercontent.com/5122581/146476954-53fef4f6-7881-4776-929a-f606b7f1f217.png">

**Comment by AlexVaPe** [comment]
Hi,

Thanks for your answer.

I've found an issue regarding the creation of the virtual environment as I cannot force it to use pyhton2.7 version:
<img width="743" alt="Captura de pantalla 2021-12-18 a las 9 22 39" src="https://user-images.githubusercontent.com/45622121/146634709-1ff85b0b-20af-49b6-a820-b54486a69995.png">

So I've been using mkvirtualenv command without specifying python version. Maybe this could be the source of the problem?

In that case, how can I install mkvirtualenv with a compatible version with python2.7? I found that my actual version of 'mkvirtualenv' is not compatible with lower versions of python, but I've tried installing a lower version but with no success.

<img width="758" alt="Captura de pantalla 2021-12-18 a las 9 25 43" src="https://user-images.githubusercontent.com/45622121/146634772-3ddf43b2-c6c4-4172-96d1-8f6de66d3c2c.png">

On the other hand, using virtualenv:
<img width="758" alt="Captura de pantalla 2021-12-18 a las 9 28 22" src="https://user-images.githubusercontent.com/45622121/146634836-ff8ee869-35df-49dd-9d21-0d3cf26ddcb2.png">

I follow exactly the same steps as shown in the README file and finally, when I type 'PyOSLC command' I'm still getting the same error:

<img width="762" alt="Captura de pantalla 2021-12-18 a las 9 32 57" src="https://user-images.githubusercontent.com/45622121/146634966-1239c43c-9f99-43e6-8d26-d7d431251152.png">



Thanks

**Comment by AlexVaPe** [comment]
Hi,

I just found the issue and now it works. I explain it just in case someone has the same problem:

Since I'm using and M1 Mac, I couldn't install virtualenv using python2.7 version, as it is not supported by arm64 architecture of M1 Macs. So, in order to use older versions of python within a virtual environment, I installed Rosetta (i386 architecture of intel emulation) and then, reinstalling virtualenv now with python 2.7 support.

With this fix, now the app is running correctly. Thank you so much for the help anyway.

Best regards
